/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class Euler2{
	int current, last, sum;
	
	public Euler2(){
		this.current = 1;
		this.last = 1;
		this.sum = 0;
	}
	
	public void run(){
		while(current < 4000000){
			int tempCurrent = current;
			int tempLast = last;
			if(current % 2 == 0)
				sum += current;
			last = tempCurrent;
			current = tempCurrent + tempLast;
		}
	}
	
	public static void main(String[] args){
		Euler2 e = new Euler2();
		e.run();
		System.out.println(e.sum);
	}
	
	
}
